### ISSUE TITLE
Events library dependency

### ISSUE THREAD

**Issue by pierreleripoll** [maplibre/maplibre-gl-geocoder#104]
Hi! I had a problem with an app I built that uses maplibre-gl-geocoder. The component wouldn't work because the events library required in index.js is not listed in the dependencies in package.json.

I added the dependency to my project's package.json, and now it works. I'm not sure if I'm doing something wrong, but maybe maplibre-gl-geocoder's package.json should have "events" in its dependencies list?

Thank you for your work on this library, though - it's great!

**Comment by HarelM** [comment]
This should be fixed by #118
