### ISSUE TITLE
collapse: true doesn't work with the Maplibre example

### ISSUE THREAD

**Issue by mem48** [maplibre/maplibre-gl-geocoder#105]
I'm trying to copy the example code https://maplibre.org/maplibre-gl-js-docs/example/geocoder/

But adding a collapsible search box using:

```
map.addControl(
  new MaplibreGeocoder(geocoder_api, {
    maplibregl: maplibregl,
    collapsed: true
  })
);
```

But it does not work.

I can get it to work in jsfiddle but the example doesn't work as a simple HTML file. See attached.

[collapsed.zip](https://github.com/maplibre/maplibre-gl-geocoder/files/10855198/collapsed.zip)

**Comment by d3netxer** [comment]
It is working for me. I also opened the collapsed zip file you linked to and it works for me there too.

**Comment by HarelM** [comment]
Closing this, if this is still relevant, please ask to reopen.
