### ISSUE TITLE
Documentation bug for auto-suggest

### ISSUE THREAD

**Issue by orenGH** [maplibre/maplibre-gl-geocoder#107]
The documentation is wrong both in [README.md](https://github.com/maplibre/maplibre-gl-geocoder/blob/main/README.md?plain=1#L22) (where it doesn't mention searchByPlaceId) and [index.js](https://github.com/maplibre/maplibre-gl-geocoder/blob/main/lib/index.js#L60-L61) (where it mentions getByPlaceId which doesn't exist in the code, also has the wrong returned values for both getByPlaceId and getSuggestions).

This adds unnecessary pain to developers, since they need to reverse-geocode the code to understand how to implement search with auto suggest.

**Comment by HarelM** [comment]
Looks like this was resolved by #108, if this is not the case please open a new issue.
