### ISSUE TITLE
Idea: able to have zoom option override bbox

### ISSUE THREAD

**Issue by d3netxer** [maplibre/maplibre-gl-geocoder#109]
When I am searching for some points, for example 'Paris'. It zooms in really far, more than I would like. 

It seems like the geocoding result is a point, but still has a bbox property?

If so, I think it would be a good idea if specified by the user, to have the zoom option be able to override a feature's bbox

**Comment by HarelM** [comment]
I think this is configurable in one way or another, if this is not the case, please request to reopen with a better definition of the API changes that would solve this issue.
