### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-geocoder#112]
Does this package has typescript types?
Is it possible to add support for typescript?

**Comment by danawoodman** [comment]
Would love built-in/bundled types!

**Comment by HarelM** [comment]
@thaddmt do you need help with this?

**Comment by thaddmt** [comment]
@HarelM if anyone is willing to help contribute would love the help! I'm not too focused on this project right now unfortunately

**Comment by HarelM** [comment]
@danawoodman any chance for some help here?
I've started to migrate to typescript, but it seems a bit too much right now, so I think an easier approach would be to convert to es5 class and generate types from it.
I've done that in a typescript branch, but there's a need to make the js compatible with how it used to be before the change, it's a bit of a tooling headache, but not a big one.
See #117.
Feel free to open PRs against that branch.

**Comment by danawoodman** [comment]
what about using jsdoc types and a hard coded .d.ts file?

i'm not familiar with the code but will have a look

**Comment by HarelM** [comment]
A hard coded d.ts is possible, but I wanted something a bit more robust.

**Comment by danawoodman** [comment]
baby steps, a .d.ts plus jsdocs seems a step towards a TS rewrite imo

**Comment by danawoodman** [comment]
going to take a stab at this... if successful ill push up a pr

**Comment by HarelM** [comment]
Take a look at the branch I made, I think you can take the generated types from there, improve them a bit and check that into this repo.

**Comment by HarelM** [comment]
See the following PR:
- https://github.com/maplibre/maplibre-gl-geocoder/pull/118

Using this branch there's an easy way to generate the typescript.d.ts file.
The only thing missing in that branch is the conversion of the tests to typescript and the need to fix some `as any` which are probably due to incorrect or old code.
