### ISSUE TITLE
No default export

### ISSUE THREAD

**Issue by vvvyyynet** [maplibre/maplibre-gl-geocoder#150]
In my Sveltekit app I successfully installed Geocoder with `npm install --save @maplibre/maplibre-gl-geocoder`. 

However when I try to import with `import MaplibreGeocoder from '@maplibre/maplibre-gl-geocoder';` it throws an error saying that 
> [vite] The requested module '@maplibre/maplibre-gl-geocoder' does not provide an export named 'default'

Is this an issue with the build or do I overlook something?

**Comment by HarelM** [comment]
It's probably a "type": "module" issue with sveltekit that it thinks it's es instead of commonjs.
I'm not sure how to solve it with Svelte...

**Comment by HarelM** [comment]
@vvvyyynet is this still relevant? Can I close this issue?

**Comment by federicomarcantognini** [comment]
@vvvyyynet I was able to import it via dynamic import:

`onMount(async () => {
    const { default: MaplibreGeocoder } = await import('@maplibre/maplibre-gl-geocoder');
`

**Comment by HarelM** [comment]
No response, closing...
