### ISSUE TITLE
Proximity Value is not Set in Geocoder When Zoom Level is Less than 9

### ISSUE THREAD

**Issue by thaddmt** [maplibre/maplibre-gl-geocoder#16]
Noticed that when the zoom level is less than 9 the proximity value is automatically unset. There is a comment stating that if the user is looking at the whole world it doesn't make sense to set the proximity scale. While I agree with that in general it seems like this should either be configurable or the value should be set lower than 9

https://github.com/maplibre/maplibre-gl-geocoder/blob/main/lib/index.js#L747

**Comment by HarelM** [comment]
I've opened the following PR to address this issue:
- #130
