### ISSUE TITLE
Is reverseGeocode required?

### ISSUE THREAD

**Issue by starsep** [maplibre/maplibre-gl-geocoder#173]
According to README `reverseGeocode` is optional
https://github.com/maplibre/maplibre-gl-geocoder/blob/47bd8596eb29ee62eebdfcf35c7159f5accb9791/README.md?plain=1#L26-L27

But looks required in https://github.com/maplibre/maplibre-gl-geocoder/blob/47bd8596eb29ee62eebdfcf35c7159f5accb9791/lib/index.ts#L255

I got this error:
```
error TS2345: Argument of type '{ forwardGeocode: (config: GeocoderConfig) => Promise<{ features: { type: string; geometry: { type: string; coordinates: any[]; }; place_name: any; properties: any; text: any; place_type: string[]; center: any[]; }[]; }>; }' is not assignable to parameter of type 'MaplibreGeocoderApi'.
  Property 'reverseGeocode' is missing in type '{ forwardGeocode: (config: GeocoderConfig) => Promise<{ features: { type: string; geometry: { type: string; coordinates: any[]; }; place_name: any; properties: any; text: any; place_type: string[]; center: any[]; }[]; }>; }' but required in type 'MaplibreGeocoderApi'.

196    const newMaplibreGeocoder = new MaplibreGeocoder(nominatimGeocoder, {
                                                        ~~~~~~~~~~~~~~~~~

  node_modules/@maplibre/maplibre-gl-geocoder/dist/maplibre-gl-geocoder.d.ts:216:5
    216     reverseGeocode: (config: MaplibreGeocoderApiConfig) => Promise<{
            ~~~~~~~~~~~~~~
    'reverseGeocode' is declared here.
```

**Comment by HarelM** [comment]
Well... I've changed the code from javascript to typescript and thus this change.
You can pass an object that doesn't have a `reverseGeocode` method, but then you'd have to pass in options `reverseGeocode = false`.
I'm not aware of an easy way to type that.
The default value for reverseGeocode is false, which can indicate that this should be an optional value and also from the readme.
In any case, I don't have strong feelings either way.
Feel free to open a PR to improve this.

**Comment by starsep** [comment]
Thanks for response!
Indeed it's not clear how to type that.
For me more natural would be to have optional `reverseGeocode` considering that this option is disabled by default
https://github.com/maplibre/maplibre-gl-geocoder/blob/47bd8596eb29ee62eebdfcf35c7159f5accb9791/lib/index.ts#L70-L74

I resolved the issue for myself by implementing empty `reverseGeocode` result in https://github.com/openstreetmap-polska/openaedmap-frontend/commit/a887041054618c734dd11afe70e07b6fdd83983f
