### ISSUE TITLE
Customise marker information when clicked

### ISSUE THREAD

**Issue by xinyuluo** [maplibre/maplibre-gl-geocoder#18]
Hi, I'm new to this API. Is it possible to customise popup information about a place when the marker is clicked? For instance, here my address is too long and it won't be able to fix into the default popup box. 

![image](https://user-images.githubusercontent.com/25223376/142160119-48db3879-f500-4800-b0ac-97359ac06160.png)

Thanks a lot!

**Comment by thaddmt** [comment]
There isn't great documentation on this currently but the [popupRender](https://github.com/maplibre/maplibre-gl-geocoder/blob/main/API.md#parameters) option allows you to specify the how the popup is rendered.

An example of the render function is in the library here - https://github.com/maplibre/maplibre-gl-geocoder/blob/main/lib/index.js#L105

Will definitely try to add more documenting examples around this in the future or simplify the API in the future. Also open to PR's to help improve the experience :)

**Comment by xinyuluo** [comment]
yep I managed to change `popRender` to have my customised popup tag, thank you :)

> Also open to PR's to help improve the experience :)

sure, I can add my example in a PR
