### ISSUE TITLE
_onKeyDown not working when map is inside custom web component

### ISSUE THREAD

**Issue by Miggets7** [maplibre/maplibre-gl-geocoder#19]
When using maplibre In a custom web component, the selection for the value doesn't work properly. The Active element in  the shadow root isn't the input element itself. My recommendation would be to use the value of  ```this._inputEl``` because there's already a reference to it.
![Screen Shot 2021-12-20 at 12 01 09](https://user-images.githubusercontent.com/29022743/146757600-3b637cc5-7264-46f8-a43d-365cdb1235c7.png)

**Comment by HarelM** [comment]
@Miggets7 can you please open a PR if this is still relevant?
I've refactored the code havily, it should be easier now to change the relevant code.

**Comment by HarelM** [comment]
No response, closing this issue.
If this is still relevant please reply and I'll reopen it.
