### ISSUE TITLE
What are the urls for script and stylesheet ?

### ISSUE THREAD

**Issue by lbcsy** [maplibre/maplibre-gl-geocoder#20]
In Mapbox, I need to use below urls for adding a Geocoder control to the map on an html page, so what is the equivalent urls for maplibr-gl-geocoder of below:
<html>
<header>

    <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.2/mapbox-gl-geocoder.min.js'></script>
    <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.2/mapbox-gl-geocoder.css' type='text/css' />
</header>
</html>

**Comment by ttomasz** [comment]
@lbcsy here's an example https://maplibre.org/maplibre-gl-js-docs/example/geocoder/

**Comment by HarelM** [comment]
If this is still relevant, please open a different issue.
