### ISSUE TITLE
options.popup defaults to "false", but documented as "true"

### ISSUE THREAD

**Issue by slaymance** [maplibre/maplibre-gl-geocoder#21]
The `options.popup` parameter to `MaplibreGeocoder` is defaulted to `false` while the JSDoc definition and reference in `API.md` specify the default value of `options.popup` as `true`.

We can resolve this by either:
- Setting the default value of `options.popup` to `true` ([L87](https://github.com/maplibre/maplibre-gl-geocoder/blob/main/lib/index.js#L87))
- Updating the JSDoc description ([L47](https://github.com/maplibre/maplibre-gl-geocoder/blob/main/lib/index.js#L47)) and the reference in `API.md` ([L99](https://github.com/maplibre/maplibre-gl-geocoder/blob/main/API.md?plain=1#L99)) to a default value of `false`

Updating reference to the default value has the benefit of not impacting users' applications if they upgrade to the version which contains the fix.

**Comment by HarelM** [comment]
I think updating the docs is the right approach at this point, feel free to submit a PR.

**Comment by HarelM** [comment]
Should be fixed by #118 
You can check out the new docs at https://www.maplibre.org/maplibre-gl-geocoder/
