### ISSUE TITLE
Pin stays on the map when results of subsequent queries return

### ISSUE THREAD

**Issue by xinyuluo** [maplibre/maplibre-gl-geocoder#48]
Hi! thanks for the amazing project. I have encountered what I think is a bug, because i think it should be irrelevant to my choice of geocoder (Nominatim).

To reproduce the bug:
1. search for "NUS singapore" (I have a map of singapore), press enter.
2. click on the one that says National University of Singapore from the dropdown list, it zooms in closer to the place;
3. click enter again and the map zooms in even closer;
4. search for the next query "NUH singapore" (do not clear manually clear search box), which has 2 results from the drop down. But when I zoom out the map, the pin for National University of Singapore is still there. 

Please see attached screen recording for the reference.

Thank you!

https://user-images.githubusercontent.com/25223376/158390405-0ef0a3e5-9a54-490a-ad88-ef80b603d3c2.mp4

**Comment by wipfli** [comment]
Thanks for reporting. Can you share a stackblitz or something similar?

**Comment by xinyuluo** [comment]
@wipfli sure. demo is here: https://stackblitz.com/edit/web-platform-fszogw
you will need a maptiler API key to access the basemap. Do you have one?

**Comment by wipfli** [comment]
Does the one for the MapLibre examples work? `get_your_own_OpIi9ZULNHzrESv6T2vL` from https://maplibre.org/maplibre-gl-js-docs/example/canvas-source/

**Comment by xinyuluo** [comment]
Yes it will work. I've just updated stackblitz.

**Comment by wipfli** [comment]
Cool, I can reproduce the bug you reported. Is there any chance that you can fix this behavior? I would be happy to review a pull request...

**Comment by wipfli** [comment]
Maybe one has to loop through features. Here is a different example where I made only one marker being highlighted: https://codesandbox.io/s/hopeful-elion-w04kb6

**Comment by xinyuluo** [comment]
How is the different example related to the bug? 
I will try to read code more closely when I have the bandwidth. If i can come up with a fix i will submit a PR

**Comment by wipfli** [comment]
Maybe it is not really related :S

**Comment by wipfli** [comment]
Cool, thanks @xinyuluo !

**Comment by HarelM** [comment]
Is it possible to add this nominatim example to either the main readme of this repo or the API.md?
I think nominatim is a probably the most known free geocoder in the OSM echo system.
Also I think it will be super cool to add this to Maputnik.

**Comment by HarelM** [comment]
The code after #118 should be fully typescript, which should help in solving these kind of cases, and if not, refactoring would be a lot easier.
I see that there are promises returning from the geoApi, and there might be a race condition in this case, or a missing `marker.remove` call.
It should be fairly easy to solve this I hope.
Sorry for the late response...

**Comment by HarelM** [comment]
Can you reproduce this in the following example page:
https://maplibre.org/maplibre-gl-js/docs/examples/geocoder/
I can't reproduce it...

**Comment by HarelM** [comment]
No response, closing for now.
If this is still relevant, please let me know and I'll reopen.
